[package]
name = "mandelbrot"
version = "0.1.0"
authors = ["Sky <sky@thelook.cn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.3.0"